version: '3.9'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
 
  web:
    build: ./test_drf_authorization/
    container_name: django
    command: python manage.py runserver  0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

volumes:
  pg_data: