version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
 
  web:
    build: ./test_drf_authorization/
    command: python manage.py runserver  0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

volumes:
  pg_data: