version: '3.9'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 5s
        timeout: 5s
        retries: 15
  
  migrate:
    build: ./test_drf_authorization/
    container_name: django_migrate
    command: python manage.py migrate
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
 
  web:
    build: ./test_drf_authorization/
    container_name: django
    command: python manage.py runserver  0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pg_data: