# Generated by Django 5.0.4 on 2024-04-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='pbkdf2_sha256$720000$lst0CPn2Jzzl8reBVPDqUM$9+PjkJyYYdpLGqfPdT3KyggMg3jHuvrJAiiQ4GTMFGQ=', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='2PiXLm', max_length=6, verbose_name='Инвайт-код'),
        ),
    ]
