# Generated by Django 5.0.4 on 2024-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='pbkdf2_sha256$720000$u2RmJdsIw1yeDWs3NaUV9m$0MS5OSglF2qCTVIn8YB8AOs6tlD6lvT4jg1Atp9BZ9c=', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='bqnAuW', max_length=6, unique=True, verbose_name='Инвайт-код'),
        ),
    ]
