# Generated by Django 5.0.4 on 2024-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_callbacktoken_key_alter_user_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='pbkdf2_sha256$720000$53XrRExecNAGBK0Aean8zH$DIXAs8r8f9/hIMM3erKFJF32O+WFK4ZET7wb7J0cjEg=', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='NeD6xs', max_length=6, verbose_name='Инвайт-код'),
        ),
    ]
