# Generated by Django 5.0.4 on 2024-04-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_callbacktoken_key_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='6881', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='N9bA98', max_length=6, verbose_name='Инвайт-код'),
        ),
    ]
