# Generated by Django 5.0.4 on 2024-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_created_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='pbkdf2_sha256$720000$PVg8WAMctCh30OLs8vSq3o$aFMY6kFTgcfWY6HaPnE1KxLGLPHLpGXysQbQdlzpWSs=', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='H2FbNE', max_length=6, verbose_name='Инвайт-код'),
        ),
    ]
