# Generated by Django 5.0.4 on 2024-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_callbacktoken_key_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default='pbkdf2_sha256$720000$H0uMgDRqTrgfz2iUp1px9w$4h/qb59eT+t24VjE+xglaPoUDCE/Gt4r1+vl/wNQSvo=', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='EKcZzV', max_length=6, verbose_name='Инвайт-код'),
        ),
    ]
